import os
from pathlib import Path

VLLM_API_KEY = os.environ.get("VLLM_API_KEY", "")

MAX_COMPLETION_TOKENS         = 4096
MAX_COMPLETION_TOKENS_THINKING = 16384
MAX_CONTINUATION_ROUNDS = 5
CONTINUE_PROMPT = "계속"
CONTINUE_PROMPT_THINKING = "계속"
ARCHIVE_THRESHOLD    = 0.75
KEEP_RECENT_TURNS    = 4
MAX_RETRIEVED_MEMORIES = 5
DB_PATH = Path("memory.db")
